---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: ensure generated directory exists
  local_action:
    module: file
    path: generated/
    state: directory

- name: load variables
  include_vars:
    file: "{{ outer_item }}"
    name: __ibm_infosvr_openigc_assets

- name: generate asset XML from variables
  local_action:
    module: template
    src: assets.xml.j2
    dest: generated/{{ outer_item | basename }}.xml

- name: load asset instances
  include_tasks: assets.yml
  vars:
    assets_as_xml:
      - generated/{{ outer_item | basename }}.xml
